version: 3
tasks:
  default:
    desc: List available tasks
    cmd: task --list-all
  rebuild:
    desc: Rebuild NixOS using flake.nix
    platforms:
      - linux
    deps:
      - remove-tofi-drun-cache
    cmds:
      - cmd: git status --porcelain '*.nix' '**/*.nix' | grep '^??' > /dev/null && echo -e "\033[33m\nWARNING\033[0m There are unstaged Nix files. The rebuild might fail.\n" || exit 0
        silent: true
      - cmd: nixos-rebuild switch --use-remote-sudo --flake .
  upgrade:
    desc: Upgrade installed programs
    platforms:
      - linux
    cmds:
      - nix flake update
      - task: nixos-rebuild
  remove-tofi-drun-cache:
    internal: true
    desc: Remove tofi-drun cache, so tofi-drun has a up-to-date list of programs
    platforms:
      - linux
    cmd: rm --force $XDG_CACHE_HOME/tofi-drun
