version: 3
tasks:
  default:
    desc: List available tasks
    cmd: task --list-all
  .flake-check:
    internal: true
    cmd: git status --porcelain '*.nix' '**/*.nix' | grep '^??' > /dev/null && echo -e "\033[33m\nWARNING\033[0m There are unstaged Nix files. The rebuild might fail.\n" || exit 0
    silent: true
  rebuild:
    desc: Rebuild NixOS using flake.nix
    platforms: [linux]
    cmds:
      - task: .flake-check
      - cmd: nixos-rebuild switch --use-remote-sudo --flake .
  rebuild-boot:
    desc: Rebuild NixOS boot and kernel options using flake.nix
    platforms: [linux]
    cmds:
      - task: .flake-check
      - cmd: nixos-rebuild boot --use-remote-sudo --flake .
  upgrade:
    desc: Upgrade installed programs
    cmds:
      - platforms: [linux]
        cmd: nix flake update
      - platforms: [darwin]
        cmd: brew bundle install --verbose
      - task: rebuild
  rollback:
    desc: Rollback to the previous NixOS build
    platforms: [linux]
    prompt: About to rollback to the previous build. Proceed?
    cmds:
      - nixos-rebuild switch --use-remote-sudo --rollback
  run-uhk-agent:
    desc: Runs UHK Agent from the unstable NixOS channel
    platforms: [linux]
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    cmds:
      - nix run github:nixos/nixpkgs/nixos-unstable#uhk-agent --impure
