version: 3
tasks:
  nixos-rebuild:
    desc: Rebuild NixOS using flake.nix
    platforms:
      - linux
    deps:
      - remove-tofi-drun-cache
    cmds:
      - git status --porcelain '*.nix' '**/*.nix' | grep '^??' > /dev/null && echo -e "\033[33m\nWARNING\033[0m There are unstaged Nix files. The rebuild might fail.\n" || exit 0
      - nixos-rebuild switch --use-remote-sudo --flake .
  remove-tofi-drun-cache:
    desc: Remove tofi-drun cache, so tofi-drun has a up-to-date list of programs
    platforms:
      - linux
    cmd: rm --force $XDG_CACHE_HOME/tofi-drun
