colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 0
default_minute: 0
editor: nvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  personal: ~/.local/share/jrnl/personal
linewrap: 79
tagsymbols: '#@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.8.4
