#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[ui]
default-command = ["l", "-n", "10"]

[user]
name = "Tymoteusz Makowski"
email = "tymek.makowski@gmail.com"

[signing]
behavior = "own"
backend = "ssh"

[aliases]
l = ["log", "-r",  "present(@) | ancestors(immutable_heads()..) | present(trunk())"]
