[ui]
default-command = ["log", "-n", "10"]

[user]
name = "Tymoteusz Makowski"
email = "tymek.makowski@gmail.com"

[signing]
behavior = "own"
backend = "ssh"

[revsets]
log = "present(@) | ancestors(immutable_heads()) | present(trunk())"
