vim.opt.colorcolumn = "+1"
vim.opt.conceallevel = 1
vim.opt.completeopt = { "menu", "menuone", "noselect" }
vim.opt.expandtab = true
vim.opt.foldenable = false
vim.opt.history = 1000
vim.opt.hlsearch = false
vim.opt.lazyredraw = true
vim.opt.list = true
vim.opt.listchars:append({ extends = ">", precedes = "<", eol = "⏎" })
vim.opt.mouse = nil
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 3
vim.opt.shiftwidth = 2
vim.opt.shortmess:append({ c = true, I = true })
vim.opt.sidescrolloff = 5
vim.opt.signcolumn = "yes"
vim.opt.smartindent = true
vim.opt.softtabstop = 2
vim.opt.spelllang = { "en", "pl" }
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.ttimeoutlen = 100
vim.opt.undofile = true
vim.opt.updatetime = 50
vim.opt.winwidth = 87
vim.opt.wrap = false
