local o = vim.opt

o.colorcolumn = "+1"
o.expandtab = true
o.foldlevelstart = 99
o.history = 1000
o.hlsearch = false
o.lazyredraw = true
o.list = true
o.listchars:append({ extends = ">", precedes = "<", eol = "⏎" })
o.mouse = "n"
o.number = true
o.relativenumber = true
o.scrolloff = 3
o.shiftwidth = 2
o.shortmess:append({ c = true })
o.sidescrolloff = 5
o.signcolumn = "yes"
o.smartindent = true
o.softtabstop = 2
o.spelllang = { "en", "pl" }
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.tabstop = 2
o.ttimeoutlen = 100
o.undofile = true
o.updatetime = 50
o.winwidth = 87
o.wrap = false
