vim.opt.colorcolumn = "+1"
vim.opt.expandtab = true
vim.opt.foldenable = false
vim.opt.hlsearch = false
vim.opt.list = true
vim.opt.listchars:append({ extends = ">", precedes = "<", eol = "⏎" })
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 3
vim.opt.shiftwidth = 2
vim.opt.shortmess:append({ I = true })
vim.opt.sidescrolloff = 5
vim.opt.signcolumn = "yes"
vim.opt.smartindent = true -- TODO: remove once I configure indentexpr with conform.nvim
vim.opt.softtabstop = 2
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.ttimeoutlen = 100
vim.opt.undofile = true
vim.opt.wildchar = 0
vim.opt.wrap = false
